// CH-03 go.mod / go.sum drift carve-out helper. CH-03
// (cachicamas-chat-http-surface) is the recorded exception:
// the chat archetype's HTTP+SSE surface requires
// github.com/labstack/echo/v5 v5.2.1 (ADR adr/echo-v5-in-agent-module,
// recorded at the start of CH-03's SDD flow), bumping the agent
// module's go.mod from 3 require lines (AI-37) to 4. Every
// byte-unchanged / scope-fence / substrate guard that checks
// go.mod + go.sum against the main branch calls this helper. The
// helper admits the diff only when the diff is the recorded
// Echo require line plus its go.sum entries — every other
// modification fails the guard normally.
//
// The function lives in this test-only file because the
// byte-unchanged / scope-fence guards above ARE the test
// fixtures; a production-source helper would be excluded
// from those guards' byte-unchanged proofs and the helpers
// would not be able to call it.

package agent_test

import "strings"

// isCH03GoModDrift reports whether diff is the recorded CH-03
// exception: the only change is the Echo require line plus the
// matching go.sum entries (the go.sum file is regenerated by
// `go mod tidy`, so the recorded exception admits ALL go.sum
// additions alongside the Echo entry — but no other go.mod
// change). It returns false for empty diffs (the caller's
// `if len(modDiff) != 0` branch handles emptiness separately)
// and false for any go.mod edit beyond the documented exception.
func isCH03GoModDrift(diff string) bool {
	if diff == "" {
		return false // empty diff is the caller's PASS path
	}

	// go.sum is regenerated by `go mod tidy`; the recorded
	// exception admits any go.sum addition alongside the Echo
	// go.mod entry. The single structural property we require
	// for go.mod diffs: no replace directive, no second new
	// require, no require removed.
	lines := strings.Split(diff, "\n")
	var goModAdd []string
	inGoMod := false
	for _, line := range lines {
		// Track which file each hunk belongs to so we apply
		// the rule only to the go.mod portion.
		if strings.HasPrefix(line, "diff --git") {
			inGoMod = strings.Contains(line, "backend/agent/go.mod")
			continue
		}
		if !inGoMod {
			continue
		}
		if !strings.HasPrefix(line, "+") || strings.HasPrefix(line, "+++") {
			continue
		}
		stripped := strings.TrimPrefix(line, "+")
		goModAdd = append(goModAdd, stripped)
	}
	if len(goModAdd) == 0 {
		// go.sum-only diff is admissible alongside the Echo bump;
		// the caller's emptiness check has already passed for
		// the go.mod portion.
		return true
	}
	for _, added := range goModAdd {
		// The require block lands entries as `	module version`.
		if !strings.HasPrefix(added, "\t") {
			// Non-indented entry: an outside-require-block change
			// (NOT what `go mod` produces).
			return false
		}
		// The single allowed require line is github.com/labstack/echo/v5.
		if !strings.HasPrefix(added, "\tgithub.com/labstack/echo/v5 ") {
			return false
		}
	}
	return true
}
