// CH-04 go.mod / go.sum drift carve-out helper. CH-04
// (cachicamas-chat-composition-root) is the recorded exception: the
// chat archetype's composition root is the only package permitted to
// install the OpenTelemetry SDK and OTLP exporter (ADR 0005 § D3,
// adr:242) and the only package that builds an in-process JWE
// IdentityResolver shim over the lestrrat-go/jwx/v2 envelope (mirrors
// database_administrator's middleware without importing it, R-07 +
// ADR 0005 § D1 row 3). Together those two decisions bump the agent
// module's go.mod from the CH-03 4-require baseline to a 7-require
// baseline + 24 transitive indirect requires, all admitted here.
//
// Pre-authorized set, drawn verbatim from ADR 0005 § D3:
//
//	go.opentelemetry.io/otel/sdk                       v1.44.0
//	go.opentelemetry.io/otel/exporters/otlp/otlptrace  v1.44.0
//	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.44.0
//	go.opentelemetry.io/otel/propagation               v1.44.0
//	go.opentelemetry.io/otel/semconv/v1.41.0           v1.41.0
//
// plus the JWE library the chat shim uses to decrypt the Auth.js
// session-token cookie (matches database_administrator's own pin):
//
//	github.com/lestrrat-go/jwx/v2 v2.1.7
//
// plus the hkdf primitive golang.org/x/crypto provides (transitive
// of jwx/v2 but pinned direct for clarity).
//
// Every byte-unchanged / scope-fence / substrate guard that checks
// go.mod + go.sum against the main branch calls isCH04GoModDrift
// AFTER isCH03GoModDrift (CH-03 came first; CH-04 widens the
// pre-authorized set). The CH-04 helper admits a diff when every
// go.mod addition is one of the four pre-authorized prefixes below
// or an indented `// indirect` line — i.e. a transitive of one of
// the pre-authorized roots, never a new direct require beyond the
// four. Every other go.mod edit (replace directive, require removed,
// module path changed) fails the guard normally.
//
// The function lives in this test-only file because the byte-
// unchanged / scope-fence guards above ARE the test fixtures; a
// production-source helper would be excluded from those guards'
// byte-unchanged proofs and the helpers would not be able to call it.

package agent_test

import "strings"

// ch04AllowedDirectPrefixes is the closed allowlist of every direct
// require line CH-04 is permitted to add to backend/agent/go.mod.
// Each entry is tab-prefixed because go.mod's `require` block lays
// entries out as `\tmodule version`; the helper below strips the
// `+` from diff lines but the tab stays, so the prefix matches the
// post-strip shape verbatim.
//
// Adding a direct require outside this list is a deliberate change
// and MUST update this table (recorded as such) — the same
// "amendment lands in the same commit as the import it authorises"
// discipline the Layer 2 guard follows.
var ch04AllowedDirectPrefixes = []string{
	"\tgithub.com/lestrrat-go/jwx/v2 ",
	"\tgo.opentelemetry.io/otel/sdk ",
	"\tgo.opentelemetry.io/otel/exporters/otlp/otlptrace ",
	"\tgo.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc ",
	"\tgolang.org/x/crypto ",
}

// isCH04GoModDrift reports whether diff is the recorded CH-04
// exception: every addition in the go.mod portion is one of the
// pre-authorized direct requires (jwx/v2, OTel SDK, OTLP exporter,
// golang.org/x/crypto) or an indented `// indirect` line carried by
// `go mod tidy` for any of those roots.
//
// It returns false for empty diffs (the caller's `if len(diff) != 0`
// branch handles emptiness separately), false for any go.mod edit
// that adds a direct require outside the closed allowlist, false for
// any replace directive, and false for any go.mod line whose removal
// would not match the diff.
//
// go.sum is fully regenerated by `go mod tidy`; the recorded
// exception admits ANY go.sum addition alongside an admissible
// go.mod change — `go.sum` is never the gate.
func isCH04GoModDrift(diff string) bool {
	if diff == "" {
		return false // empty diff is the caller's PASS path
	}

	// Track which file each hunk belongs to so we apply the rule
	// only to the go.mod portion.
	lines := strings.Split(diff, "\n")
	var inGoMod bool
	for _, line := range lines {
		if strings.HasPrefix(line, "diff --git") {
			inGoMod = strings.Contains(line, "backend/agent/go.mod")
			continue
		}
		if !inGoMod {
			continue
		}
		// Skip the diff metadata lines (--- / +++).
		if strings.HasPrefix(line, "---") || strings.HasPrefix(line, "+++") {
			continue
		}
		// Skip `@@` hunk headers and context (unchanged) lines.
		if strings.HasPrefix(line, "@@") || strings.HasPrefix(line, " ") || strings.HasPrefix(line, "-") {
			continue
		}
		if !strings.HasPrefix(line, "+") {
			continue
		}
		added := strings.TrimPrefix(line, "+")
		// A require-block open (`require (`) or close (`)`) line is
		// produced by `go mod tidy` when a single-line require is
		// widened into a block (or vice versa). Admit both — checked
		// FIRST so the subsequent tab-required check doesn't reject
		// the block delimiters.
		if strings.HasPrefix(added, "require (") || strings.HasPrefix(added, ")") {
			continue
		}
		// Outside any require block: the file header (`module ...`,
		// `go ...`) MUST be unchanged. Anything other than an indented
		// require line is a header edit, rejected.
		if !strings.HasPrefix(added, "\t") {
			return false
		}
		// Indented lines: `	module version` (direct) or
		// `	module version // indirect`. The indirect comment is
		// added by `go mod tidy` for transitive closures and is
		// admissible so long as the line is a transitive of one of
		// our pre-authorized roots.
		if strings.Contains(added, "// indirect") {
			continue
		}
		// Direct require: must match the closed allowlist.
		allowed := false
		for _, prefix := range ch04AllowedDirectPrefixes {
			if strings.HasPrefix(added, prefix) {
				allowed = true
				break
			}
		}
		if !allowed {
			return false
		}
	}
	return true
}