// CH-07 go.mod / go.sum drift carve-out helper. CH-07
// (cachicamas-chat-store-adapter) is the recorded exception: the
// chat archetype owns the database adapter behind the CH-06 port and
// the chat-owned forward-only migration runner. Both admit two new
// top-level Go deps in `backend/agent/go.mod`:
// github.com/jackc/pgx/v5 and github.com/pressly/goose/v3 (ADR
// 0010-add-pgx-and-goose-to-backend-agent.md, the same-PR ADR
// required by `openspec/AGENTS.md` Hard Rule 5). The agent module
// goes from the CH-04 7-require baseline to a 9-require baseline +
// pgx's transitive closure (puddle, pgpassfile, pgservicefile,
// interpolate) + goose's transitive closure (sethvargo/go-retry,
// multierr, x/text, x/sync), all admitted here.
//
// Pre-authorized set, drawn verbatim from ADR 0010:
//
//	github.com/jackc/pgx/v5 v5.10.0
//	github.com/pressly/goose/v3 v3.27.1
//
// Every byte-unchanged / scope-fence / substrate guard that checks
// go.mod + go.sum against the main branch calls isCH07GoModDrift
// AFTER isCH03GoModDrift and isCH04GoModDrift (CH-03 came first,
// CH-04 widened the pre-authorized set; CH-07 widens it again). The
// CH-07 helper admits a diff when every go.mod addition is one of the
// two pre-authorized prefixes below or an indented `// indirect`
// line — i.e. a transitive of one of the pre-authorized roots, never
// a new direct require beyond the two. Every other go.mod edit
// (replace directive, require removed, module path changed) fails
// the guard normally.
//
// The function lives in this test-only file because the byte-
// unchanged / scope-fence guards above ARE the test fixtures; a
// production-source helper would be excluded from those guards'
// byte-unchanged proofs and the helpers would not be able to call it.

package agent_test

import "strings"

// ch07AllowedDirectPrefixes is the closed allowlist of every direct
// require line CH-07 is permitted to add to backend/agent/go.mod.
// Each entry is tab-prefixed because go.mod's `require` block lays
// entries out as `\tmodule version`; the helper below strips the
// `+` from diff lines but the tab stays, so the prefix matches the
// post-strip shape verbatim.
//
// Adding a direct require outside this list is a deliberate change
// and MUST update this table (recorded as such) — the same
// "amendment lands in the same commit as the import it authorises"
// discipline the Layer 2 guard follows.
var ch07AllowedDirectPrefixes = []string{
	"\tgithub.com/jackc/pgx/v5 ",
	"\tgithub.com/pressly/goose/v3 ",
}

// isCH07GoModDrift reports whether diff is the recorded CH-07
// exception: every addition in the go.mod portion is one of the
// pre-authorized direct requires (pgx/v5, goose/v3) or an indented
// `// indirect` line carried by `go mod tidy` for any of those roots.
//
// It returns false for empty diffs (the caller's `if len(diff) != 0`
// branch handles emptiness separately), false for any go.mod edit
// that adds a direct require outside the closed allowlist, false for
// any replace directive, and false for any go.mod line whose removal
// would not match the diff.
//
// go.sum is fully regenerated by `go mod tidy`; the recorded
// exception admits ANY go.sum addition alongside an admissible
// go.mod change — `go.sum` is never the gate.
func isCH07GoModDrift(diff string) bool {
	if diff == "" {
		return false // empty diff is the caller's PASS path
	}

	// Track which file each hunk belongs to so we apply the rule
	// only to the go.mod portion.
	lines := strings.Split(diff, "\n")
	var inGoMod bool
	for _, line := range lines {
		if strings.HasPrefix(line, "diff --git") {
			inGoMod = strings.Contains(line, "backend/agent/go.mod")
			continue
		}
		if !inGoMod {
			continue
		}
		// Skip the diff metadata lines (--- / +++).
		if strings.HasPrefix(line, "---") || strings.HasPrefix(line, "+++") {
			continue
		}
		// Skip `@@` hunk headers and context (unchanged) lines.
		if strings.HasPrefix(line, "@@") || strings.HasPrefix(line, " ") || strings.HasPrefix(line, "-") {
			continue
		}
		if !strings.HasPrefix(line, "+") {
			continue
		}
		added := strings.TrimPrefix(line, "+")
		// A require-block open (`require (`) or close (`)`) line is
		// produced by `go mod tidy` when a single-line require is
		// widened into a block (or vice versa). Admit both — checked
		// FIRST so the subsequent tab-required check doesn't reject
		// the block delimiters.
		if strings.HasPrefix(added, "require (") || strings.HasPrefix(added, ")") {
			continue
		}
		// Outside any require block: the file header (`module ...`,
		// `go ...`) MUST be unchanged. Anything other than an indented
		// require line is a header edit, rejected.
		if !strings.HasPrefix(added, "\t") {
			return false
		}
		// Indented lines: `	module version` (direct) or
		// `	module version // indirect`. The indirect comment is
		// added by `go mod tidy` for transitive closures and is
		// admissible so long as the line is a transitive of one of
		// our pre-authorized roots.
		if strings.Contains(added, "// indirect") {
			continue
		}
		// Direct require: must match the closed allowlist.
		allowed := false
		for _, prefix := range ch07AllowedDirectPrefixes {
			if strings.HasPrefix(added, prefix) {
				allowed = true
				break
			}
		}
		if !allowed {
			return false
		}
	}
	return true
}