/**
 * Behavioural spec for `routes/settings/prompts/index.tsx`.
 *
 * First behavioural spec for this route — fills the gap that
 * allowed the hardcoded `href="/home"` back-link bug to survive
 * PR #51 (which shipped the `/settings` launcher). The route
 * pre-dated the launcher, and the back affordance was a relic
 * from when `/home` was the closest "up" ancestor. Now that
 * `/settings` is the launcher and `/settings/prompts` lives
 * below it, a hardcoded `/home` is wrong on two counts:
 *   1. Navigation flow: clicking "Back" should go to wherever
 *      the user came from, not a guessed URL.
 *   2. Maintenance: hardcoded paths bake in assumptions that
 *      rot as flows evolve. Semantic actions (history.back())
 *      survive.
 *
 * User quote: "I prefer the real back, I mean the ease solution
 * is not the proper one, it fixes faster but in the time this
 * will be difficult to mantain."
 *
 * The back affordance MUST therefore be:
 *   - a real-history back, NOT a hardcoded link
 *   - a <button> (declarative URL → imperative action)
 *   - href-free (history.back() is not a URL)
 *
 * Mock strategy — Qwik City context stub:
 *   The route uses `routeLoader$` + `Link` + `useNavigate`. In
 *   createDOM() there is no Qwik City provider, so the loader's
 *   `useContext(RouteStateContext)` would throw ("undefined")
 *   and `Link`'s `useNavigate` would throw ("qc-n"). We provide
 *   the eight Qwik City contexts (qc-s / qc-c / qc-ic / qc-h /
 *   qc-l / qc-n / qc-a / qc-p) from a wrapper component, using
 *   the same string IDs that `@builder.io/qwik-city` uses
 *   internally. The loaderState shape mirrors the real
 *   `QwikCityProvider`: a `useStore` with a signal at
 *   `[loader.__id].value`.
 *
 *   `usePromptsLoader.__id` is the loader's hash, generated by
 *   the Qwik optimizer at build time. Reading it at test time
 *   keeps the test resilient to hash regeneration across rebuilds.
 *
 * RED step:
 *   As long as the route still ships `<Link href="/home">` for
 *   the back affordance, the first two tests fail:
 *     - tagName is "A", not "BUTTON"
 *     - href attribute is "/home", not null
 *   Tests 3 and 4 may pass under the legacy link (text "Back" +
 *   testid already exist), which is fine — they guard against
 *   regressions in the GREEN commit, not against the bug itself.
 */
import { createDOM } from "@builder.io/qwik/testing";
import {
  createContextId,
  useContextProvider,
  component$,
  useStore,
  useSignal,
  $,
} from "@builder.io/qwik";
import { describe, it, expect, vi } from "vitest";

// Mock the prompts-api so listPrompts() returns an empty list. This
// is belt-and-braces: the loaderState stub below already short-
// circuits the loader's network call, but if any other component
// code path reaches listPrompts() (e.g. retry handler), the mock
// keeps the test deterministic.
vi.mock("~/lib/prompts-api", () => ({
  listPrompts: vi.fn(async () => ({ ok: true as const, value: [] })),
  getPrompt: vi.fn(),
  createPrompt: vi.fn(),
  updatePrompt: vi.fn(),
  deletePrompt: vi.fn(),
  listRevisions: vi.fn(),
  restoreRevision: vi.fn(),
}));

// The loader also calls `requireOwnboarding(event)`. createDOM()
// does not provide a full RequestEvent, so mock the guard as a
// no-op. (The loaderState stub below short-circuits the loader
// entirely, but the guard mock keeps `onRequest` (also exported
// from this module) testable in isolation if we ever add tests.)
vi.mock("~/lib/require-ownboarding", () => ({
  requireOwnboarding: vi.fn(async () => undefined),
}));

vi.mock("~/lib/ssr-cookie-context", () => ({
  setSsrCookieHeader: vi.fn(),
}));

vi.mock("~/lib/require-auth-redirect", () => ({
  requireAuthRedirect: vi.fn(),
}));

// The default `qwikCity()` Vite plugin is registered, but no
// QwikCityProvider is mounted for the test render. Provide a
// stub `useContextProvider` for the eight Qwik City contexts via
// a wrapper. The string IDs ("qc-s", "qc-c", etc.) mirror the
// ones @builder.io/qwik-city creates internally — context lookup
// is keyed by string, so a fresh createContextId with the same
// string is interchangeable with Qwik City's private one.
import Index, { usePromptsLoader } from "./index";

// `__id` is a Qwik City internal stamped onto every `routeLoader$`
// at build time. It is not part of the public type, but it IS the
// key Qwik City uses to look up the loader's value in
// `RouteStateContext`. Cast to the internal shape so tsc accepts
// the access without an `as any` escape hatch.
type LoaderWithId = { __id: string };
const loaderId = (usePromptsLoader as unknown as LoaderWithId).__id;

const QC_S = createContextId<Record<string, unknown>>("qc-s");
const QC_C = createContextId("qc-c");
const QC_IC = createContextId("qc-ic");
const QC_H = createContextId("qc-h");
const QC_L = createContextId("qc-l");
const QC_N = createContextId<(path: string) => Promise<void>>("qc-n");
const QC_A = createContextId("qc-a");
const QC_P = createContextId("qc-p");

const TestWrapper = component$(() => {
  // Stub loaderState: a useStore with a signal at [loader.__id].
  // The loader hook reads `_wrapProp(state, id)` — when state[id]
  // is a signal, _wrapProp returns the signal itself, so callers
  // can do `loader.value.foo`. Setting `signal.value = { ok, prompts }`
  // gives us exactly the shape QwikCityProvider would inject after
  // a real loader resolution.
  const loaderState = useStore<Record<string, unknown>>(
    { [loaderId]: useSignal() },
    { deep: false },
  );
  (loaderState[loaderId] as { value: unknown }).value = {
    ok: true as const,
    prompts: [],
  };

  // Stubs for the other Qwik City contexts. Most are no-ops;
  // only RouteNavigateContext needs a function shape (used by the
  // existing <Link> component via useNavigate).
  useContextProvider(QC_S, loaderState);
  useContextProvider(QC_C, { headings: undefined, menu: undefined });
  useContextProvider(QC_IC, undefined);
  useContextProvider(QC_H, {
    title: "",
    frontmatter: undefined,
    meta: [],
    links: [],
    styles: [],
  });
  useContextProvider(QC_L, {
    url: new URL("http://localhost/settings/prompts"),
    params: {},
    isNavigating: false,
    prevUrl: undefined,
  });
  useContextProvider(QC_N, $(async (_path: string) => undefined));
  useContextProvider(QC_A, undefined);
  useContextProvider(QC_P, undefined);

  return <Index />;
});

describe("routes/settings/prompts — back affordance (real history back)", () => {
  it("back element is a <button>, NOT a <a> link (declarative URL → imperative action)", async () => {
    const { screen, render } = await createDOM();
    await render(<TestWrapper />);
    const back = screen.querySelector(
      '[data-testid="prompt-studio-back"]',
    ) as HTMLElement | null;
    expect(back).toBeTruthy();
    expect(back?.tagName).toBe("BUTTON");
  });

  it("back element has NO href attribute (history.back() is not a URL)", async () => {
    const { screen, render } = await createDOM();
    await render(<TestWrapper />);
    const back = screen.querySelector(
      '[data-testid="prompt-studio-back"]',
    ) as HTMLElement | null;
    expect(back).toBeTruthy();
    expect(back?.getAttribute("href")).toBeNull();
  });

  it("back element has visible 'Back' label (UX regression guard)", async () => {
    const { screen, render } = await createDOM();
    await render(<TestWrapper />);
    const back = screen.querySelector(
      '[data-testid="prompt-studio-back"]',
    ) as HTMLElement | null;
    expect(back).toBeTruthy();
    expect((back?.textContent ?? "").toLowerCase()).toContain("back");
  });

  it("back element exists with stable testid='prompt-studio-back' (selector stability)", async () => {
    const { screen, render } = await createDOM();
    await render(<TestWrapper />);
    expect(
      screen.querySelector('[data-testid="prompt-studio-back"]'),
    ).toBeTruthy();
  });
});
