-- +goose Up
-- +goose StatementBegin
-- Hello-world migration: prove the runner is wired end-to-end.
--
-- The body is intentionally a no-op SELECT 1. The point of this
-- migration is NOT to change schema; it is to verify that
--   (a) embed.FS picks up the file,
--   (b) goose sorts it lexicographically,
--   (c) goose inserts a row into public.schema_migrations, and
--   (d) the runner wraps the call in an OTel span + slog line.
--
-- See proposal Goals G1, G3 and spec S-DBMIG-001. Future
-- bounded-context DDL (catalog, identity, observability) lands as
-- separate timestamp-prefixed files in this directory.
--
-- Note on the goose v3.27.1 idiom: a SINGLE file with both Up
-- and Down blocks (separated by StatementEnd + StatementBegin for
-- the Down block) is the correct shape. The legacy goose v2
-- convention of an XXX.sql plus an XXX.down.sql pair is rejected
-- by goose v3 with "found duplicate migration version" because
-- both files share the numeric prefix.
SELECT 1;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Symmetric no-op down: keeps `goose down` working locally for
-- tests without changing schema. Per design Q5, schema-only changes
-- should always write a reversible down; data moves should leave a
-- TODO comment instead. This is neither - it is a smoke test - but
-- the symmetric body costs nothing.
SELECT 1;
-- +goose StatementEnd
