#!/usr/bin/env bash
# regenerate_authjs_testdata.sh — produce a committed Auth.js JWE
# fixture for the IdentityFromCookie middleware tests.
#
# Reference: openspec/changes/cachicamas-github-login/specs/backend-auth-middleware/spec.md
#   R-BAM-002 (S-BAM-020) — the JWE envelope contract is byte-level.
#   This script is the cross-tooling evidence: it runs the @auth/core
#   encoder (the SAME encoder used by the Qwik frontend at runtime)
#   against a known payload using a known AUTH_SECRET, then writes
#   the JWE to testdata/authjs_session_token.jwe. The Go verifier
#   test reads that file and asserts on the decoded plaintext, so
#   any future envelope drift breaks the test.
#
# Why this is a Node script and not Go:
#   Re-implementing Auth.js' HKDF + jose EncryptJWT in Go would be
#   re-implementing the spec, not verifying it. The point of the
#   test is to prove that an ACTUAL @auth/core encoder produces an
#   output the Go verifier can decrypt. Hence the canonical encoder
#   must produce the fixture.
#
# Usage:
#   ./scripts/regenerate_authjs_testdata.sh
#
# Reads AUTH_SECRET from env (defaults to the fixtureAuthSecret in
# auth_middleware_test.go so the default re-generates a usable
# fixture). Writes to testdata/authjs_session_token.jwe.

set -euo pipefail

# Resolve repo root from script location.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# scripts/ -> database_administrator/ -> backend/ -> repo root
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
INTERFACES_DIR="${REPO_ROOT}/backend/database_administrator/src/interfaces/http"
TESTDATA_DIR="${INTERFACES_DIR}/testdata"
JWE_FILE="${TESTDATA_DIR}/authjs_session_token.jwe"

# Pin AUTH_SECRET to the value the Go test asserts against. Override
# via env if you want a different fixture.
AUTH_SECRET_VALUE="${AUTH_SECRET:-test-secret-do-not-use-in-prod-thirtytwo-bytes!}"
COOKIE_NAME_VALUE="${AUTH_COOKIE_NAME:-authjs.session-token}"

mkdir -p "${TESTDATA_DIR}"

# Run the encoder via a temp Node script. The frontend repo (where
# @auth/core lives) must be reachable via NODE_PATH.
FRONTEND_NM="${REPO_ROOT}/frontend/node_modules"
if [[ ! -d "${FRONTEND_NM}/@auth/core" ]]; then
  echo "ERROR: ${FRONTEND_NM}/@auth/core not found. Run 'pnpm install' in frontend/ first." >&2
  exit 1
fi

TMPDIR_VALUE="$(mktemp -d)"
trap 'rm -rf "${TMPDIR_VALUE}"' EXIT

# Put encode.mjs INSIDE the frontend tree so Node's ESM resolver
# can find @auth/core via the regular package.json resolution.
ENCODE_SCRIPT="${REPO_ROOT}/frontend/scripts_tmp_encode_authjs.mjs"
mkdir -p "${REPO_ROOT}/frontend/scripts_tmp"
cat > "${ENCODE_SCRIPT}" <<EOF
import { encode } from "@auth/core/jwt";

const secret = process.env.AUTH_SECRET_VALUE;
const salt = process.env.COOKIE_NAME_VALUE;
const payload = {
  sub: "12345",
  email: "octocat@example.com",
  name: "Octocat",
  picture: "https://github.com/avatars/octo.png",
};
const maxAge = 30 * 24 * 60 * 60;
const jwe = await encode({ token: payload, secret, salt, maxAge });
process.stdout.write(jwe);
EOF

export AUTH_SECRET_VALUE
export COOKIE_NAME_VALUE

JWE_VALUE="$(cd "${REPO_ROOT}/frontend" && node --experimental-vm-modules "${ENCODE_SCRIPT}")"
rm -f "${ENCODE_SCRIPT}"

cat > "${JWE_FILE}" <<EOF
# Auth.js session-token fixture for the IdentityFromCookie middleware
# (cachicamas-github-login PR-3, S-BAM-020). Generated by:
#     backend/database_administrator/scripts/regenerate_authjs_testdata.sh
#
# AUTH_SECRET: ${AUTH_SECRET_VALUE}
# Cookie name (HKDF salt): ${COOKIE_NAME_VALUE}
# Payload (plaintext after JWE decrypt):
#     sub=12345
#     email=octocat@example.com
#     name=Octocat
#     picture=https://github.com/avatars/octo.png
#
# Do not hand-edit. Re-run the script if the envelope contract drifts.
EOF
printf '%s\n' "${JWE_VALUE}" >> "${JWE_FILE}"

echo "Wrote fixture: ${JWE_FILE}"
echo "Bytes: $(wc -c < "${JWE_FILE}")"
echo "First 60 chars: $(cut -c-60 "${JWE_FILE}")"