// Package httpiface_test contains the test suite for the IdentityFromCookie
// middleware introduced by cachicamas-github-login PR-3.
//
// Reference: openspec/changes/cachicamas-github-login/specs/backend-auth-middleware/spec.md
//
//   R-BAM-001 (S-BAM-010..S-BAM-012) — the middleware reads the JWE cookie,
//   decrypts it with AUTH_SECRET, looks up the identity, populates
//   c.Set("identity", *Identity), and returns 401 on any failure.
//   R-BAM-002 (S-BAM-020) — decryption uses lestrrat-go/jwx/v2.
//   R-BAM-003 (S-BAM-030) — middleware never emits a Set-Cookie header.
//   R-BAM-021 (S-BAM-070..S-BAM-072) — OTel span + slog line per request,
//   PII (email) is sha256(first 12 hex chars), not raw.
//   R-BAM-030 (S-BAM-080..S-BAM-081) — AUTH_SECRET must be set AND at least
//   32 raw bytes; otherwise startup crashes.
//   R-BAM-100 (S-BAM-110) — all tests pass under -race.
//
// The fixture JWE (testdata/authjs_session_token.jwe) is generated by
// `scripts/regenerate_authjs_testdata.sh`, which runs the @auth/core
// encoder against a known payload using a known AUTH_SECRET. The Go
// tests read both the JWE and the expected plaintext JSON and assert
// byte-equality. This is the load-bearing TDD evidence for the
// envelope contract documented in design §3.
package httpiface

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/labstack/echo/v5"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"

	"github.com/cachicamas/backend/database_administrator/src/domain"
)

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

const (
	// fixtureAuthSecret is the AUTH_SECRET used by the regenerate
	// script to produce the fixture JWE. Must match the script.
	fixtureAuthSecret = "test-secret-do-not-use-in-prod-thirtytwo-bytes!"
	// fixtureCookieName matches what Auth.js for Qwik emits when
	// AUTH_URL is http://localhost (insecure). Production uses
	// __Secure-authjs.session-token — exercised in a separate test.
	fixtureCookieName = "authjs.session-token"
	// fixtureExpectedEmail is the email claim inside the fixture JWE.
	// The IdentityRepository fake matches against this value.
	fixtureExpectedEmail = "octocat@example.com"
)

// loadFixtureJWE returns the committed fixture JWE from testdata. If
// the fixture is missing the test fails — the regenerate script must
// be run to produce it. The fixture file starts with a header comment
// (lines starting with #) followed by the JWE on its own line; we
// extract only the JWE line so the cookie parser doesn't choke on
// the leading comment text.
func loadFixtureJWE(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile("testdata/authjs_session_token.jwe")
	if err != nil {
		t.Fatalf("fixture missing: %v — run scripts/regenerate_authjs_testdata.sh", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		return line
	}
	t.Fatalf("fixture file has no JWE content (only header comments?)")
	return ""
}

// fakeIdentityRepo is the in-memory IdentityRepository used by these
// tests.
type fakeIdentityRepo struct {
	mu                 sync.Mutex
	byEmail            map[string]*domain.Identity
	lookupErr          error
	byProviderCalls    int
	byEmailCalls       int
	lastProviderCall   string
	lastProviderIDCall string
	lastEmailCall      string
}

func newFakeIdentityRepo() *fakeIdentityRepo {
	return &fakeIdentityRepo{
		byEmail: map[string]*domain.Identity{
			fixtureExpectedEmail: {
				ID:                42,
				Email:             fixtureExpectedEmail,
				Name:              "Octocat",
				ImageURL:          "https://github.com/avatars/octo.png",
				Provider:          "github",
				ProviderAccountID: "12345",
			},
		},
	}
}

func (r *fakeIdentityRepo) LookupByProviderAccountID(_ context.Context, provider, providerAccountID string) (*domain.Identity, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.byProviderCalls++
	r.lastProviderCall = provider
	r.lastProviderIDCall = providerAccountID
	if r.lookupErr != nil {
		return nil, r.lookupErr
	}
	for _, id := range r.byEmail {
		if id.Provider == provider && id.ProviderAccountID == providerAccountID {
			dup := *id
			return &dup, nil
		}
	}
	return nil, &domain.IdentityNotFoundError{Email: provider + "/" + providerAccountID}
}

func (r *fakeIdentityRepo) LookupByEmail(_ context.Context, email string) (*domain.Identity, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.byEmailCalls++
	r.lastEmailCall = email
	if r.lookupErr != nil {
		return nil, r.lookupErr
	}
	id, ok := r.byEmail[strings.ToLower(email)]
	if !ok {
		return nil, &domain.IdentityNotFoundError{Email: email}
	}
	return id, nil
}

func (r *fakeIdentityRepo) Upsert(_ context.Context, ev domain.IdentityEvent) (*domain.Identity, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.byProviderCalls++
	r.lastProviderCall = ev.Provider
	r.lastProviderIDCall = ev.ProviderAccountID
	if r.lookupErr != nil {
		return nil, r.lookupErr
	}
	for _, id := range r.byEmail {
		if id.Provider == ev.Provider && id.ProviderAccountID == ev.ProviderAccountID {
			dup := *id
			return &dup, nil
		}
	}
	return &domain.Identity{
		ID:                int64(len(r.byEmail) + 1),
		Email:             ev.Email,
		Name:              ev.Name,
		ImageURL:          ev.ImageURL,
		Provider:          ev.Provider,
		ProviderAccountID: ev.ProviderAccountID,
	}, nil
}

// newCapturingLogger returns an slog.Logger whose output is captured
// into a buffer the test can inspect.
func newCapturingLogger() (*slog.Logger, *bytes.Buffer) {
	buf := &bytes.Buffer{}
	return slog.New(slog.NewJSONHandler(buf, &slog.HandlerOptions{Level: slog.LevelDebug})), buf
}

// newSpanRecorder sets up an OTel span recorder so tests can assert
// that the middleware emits a span per request.
func newSpanRecorder() (*tracetest.SpanRecorder, *sdktrace.TracerProvider) {
	rec := tracetest.NewSpanRecorder()
	tp := sdktrace.NewTracerProvider(sdktrace.WithSpanProcessor(rec))
	return rec, tp
}

// newRouterWithAuth builds a tiny Echo router that mounts a single
// protected route /api/v1/protected/whoami behind the
// IdentityFromCookie middleware. The handler echoes the identity
// name it observed (or "NO_IDENTITY" if the middleware did not set
// one) and the HTTP status 200, so tests can assert both the
// identity propagation and the response.
func newRouterWithAuth(cfg IdentityMiddlewareConfig) *echo.Echo {
	e := echo.New()
	e.Use(func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c *echo.Context) error {
			ctx, span := sdktrace.NewTracerProvider().Tracer("test").Start(context.Background(), "noop")
			_ = ctx
			_ = span
			return next(c)
		}
	})
	mw := IdentityFromCookie(cfg)
	e.GET("/api/v1/protected/whoami", mw(func(c *echo.Context) error {
		v := c.Get(IdentityContextKey)
		if v == nil {
			return c.NoContent(http.StatusOK)
		}
		id, ok := v.(*domain.Identity)
		if !ok {
			return fmt.Errorf("identity has wrong type: %T", v)
		}
		c.Response().Header().Set("Content-Type", "application/json")
		return json.NewEncoder(c.Response()).Encode(map[string]any{
			"id":     id.ID,
			"email":  id.Email,
			"name":   id.Name,
			"provider": id.Provider,
		})
	}))
	return e
}

// newRequestWithCookie builds an httptest request carrying the
// authjs.session-token cookie with the given raw JWE value.
func newRequestWithCookie(t *testing.T, cookieValue string) *http.Request {
	t.Helper()
	req := httptest.NewRequest(http.MethodGet, "/api/v1/protected/whoami", nil)
	if cookieValue != "" {
		req.AddCookie(&http.Cookie{
			Name:  fixtureCookieName,
			Value: cookieValue,
		})
	}
	return req
}

// ---------------------------------------------------------------------------
// R-BAM-001 (S-BAM-010..S-BAM-012)
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_ValidCookie_PopulatesIdentity(t *testing.T) {
	// S-BAM-010: a request whose cookie carries a JWE signed by the
	// project's AUTH_SECRET + a payload whose email matches an
	// identity.user row -> middleware calls next(c) without writing
	// any response, and the downstream handler observes a non-nil
	// *Identity in c.Get("identity") with Email == payload.email.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	logger, _ := newCapturingLogger()
	rec, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})

	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	if rec2.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d body=%q", rec2.Code, rec2.Body.String())
	}
	var body map[string]any
	if err := json.Unmarshal(rec2.Body.Bytes(), &body); err != nil {
		t.Fatalf("response body is not JSON: %v body=%q", err, rec2.Body.String())
	}
	if body["email"] != fixtureExpectedEmail {
		t.Errorf("expected email %q in handler response, got %v", fixtureExpectedEmail, body["email"])
	}
	// OTel span emitted (S-BAM-070).
	if len(rec.Ended()) == 0 {
		t.Error("expected OTel span to be emitted, none found")
	}
}

func TestIdentityFromCookie_TamperedCookie_Returns401(t *testing.T) {
	// S-BAM-011: JWE issued with a DIFFERENT AUTH_SECRET -> 401 +
	// locked envelope code=unauthorized + next(c) NOT invoked.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	logger, _ := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret: "different-secret-do-not-use-also-thirtytwo-bytes!",
		CookieName: fixtureCookieName,
		IdentityRepo: repo,
		Logger:       logger,
		TracerProvider: tp,
	})

	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	if rec2.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d body=%q", rec2.Code, rec2.Body.String())
	}
	var env map[string]any
	if err := json.Unmarshal(rec2.Body.Bytes(), &env); err != nil {
		t.Fatalf("response body is not JSON: %v body=%q", err, rec2.Body.String())
	}
	if env["code"] != "unauthorized" {
		t.Errorf("expected code=unauthorized, got %v", env["code"])
	}
}

func TestIdentityFromCookie_MissingCookie_Returns401(t *testing.T) {
	// S-BAM-012: no cookie -> 401 with code=unauthorized.
	repo := newFakeIdentityRepo()
	logger, _ := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})

	req := httptest.NewRequest(http.MethodGet, "/api/v1/protected/whoami", nil)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	if rec2.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d body=%q", rec2.Code, rec2.Body.String())
	}
	var env map[string]any
	_ = json.Unmarshal(rec2.Body.Bytes(), &env)
	if env["code"] != "unauthorized" {
		t.Errorf("expected code=unauthorized, got %v", env["code"])
	}
}

// ---------------------------------------------------------------------------
// R-BAM-002 (S-BAM-020)
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_DecryptionShape(t *testing.T) {
	// S-BAM-020: decrypting the fixture JWE yields a JSON payload
	// with the canonical Auth.js JWT claims (sub, email, name,
	// picture, iat, exp, jti). Verified by side-effect: the
	// middleware passes the email claim to the IdentityRepository,
	// and our fake matches. If the envelope shape drifts, the
	// lookup would miss and the middleware would 401.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	logger, _ := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })
	_ = tp

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})

	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)
	if rec2.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d body=%q", rec2.Code, rec2.Body.String())
	}
}

// ---------------------------------------------------------------------------
// R-BAM-003 (S-BAM-030)
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_NeverEmitsSetCookie(t *testing.T) {
	// S-BAM-030: the verifier is a STATELESS reader. It MUST NOT
	// emit Set-Cookie headers under any code path (success, missing
	// cookie, tampered cookie, repo error).
	cases := []struct {
		name     string
		cookieV  string
		authSec  string
		repoErr  error
		wantCode int
	}{
		{"valid", loadFixtureJWE(t), fixtureAuthSecret, nil, http.StatusOK},
		{"tampered", loadFixtureJWE(t), "wrong-secret-thirty-two-bytes-aaaaaa", nil, http.StatusUnauthorized},
		{"missing", "", fixtureAuthSecret, nil, http.StatusUnauthorized},
		{"repo_error", loadFixtureJWE(t), fixtureAuthSecret, errors.New("db down"), http.StatusUnauthorized},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			repo := newFakeIdentityRepo()
			repo.lookupErr = tc.repoErr
			logger, _ := newCapturingLogger()
			_, tp := newSpanRecorder()
			t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

			e := newRouterWithAuth(IdentityMiddlewareConfig{
				AuthSecret:     tc.authSec,
				CookieName:     fixtureCookieName,
				IdentityRepo:   repo,
				Logger:         logger,
				TracerProvider: tp,
			})

			req := newRequestWithCookie(t, tc.cookieV)
			rec2 := httptest.NewRecorder()
			e.ServeHTTP(rec2, req)

			if rec2.Code != tc.wantCode {
				t.Errorf("expected %d, got %d body=%q", tc.wantCode, rec2.Code, rec2.Body.String())
			}
			for k, vs := range rec2.Header() {
				if strings.EqualFold(k, "Set-Cookie") {
					t.Errorf("verifier MUST NOT emit Set-Cookie, got %v=%v", k, vs)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// R-BAM-021 (S-BAM-070..S-BAM-072)
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_EmitsSlogAndSpan(t *testing.T) {
	// S-BAM-070 + S-BAM-072: a successful request emits a slog line
	// with the email HASHED (not raw). The hash is sha256(email)
	// truncated to 12 hex chars. The slog JSON handler emits fields
	// as `"key":"value"` so we match against that shape.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	logger, logBuf := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})

	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	logs := logBuf.String()
	if !strings.Contains(logs, `"msg":"auth.verify"`) {
		t.Errorf("expected slog line with msg=auth.verify, got %q", logs)
	}
	if strings.Contains(logs, fixtureExpectedEmail) {
		t.Errorf("PII leaked: raw email in logs: %q", logs)
	}
	h := sha256.Sum256([]byte(fixtureExpectedEmail))
	wantHash := hex.EncodeToString(h[:])[:12]
	wantKey := `"email_hash":"` + wantHash + `"`
	if !strings.Contains(logs, wantKey) {
		t.Errorf("expected log line to contain %q, got %q", wantKey, logs)
	}
}

// ---------------------------------------------------------------------------
// R-BAM-030 (S-BAM-080..S-BAM-081)
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_RequiresAuthSecret(t *testing.T) {
	// S-BAM-080: an empty AUTH_SECRET at construction panics.
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic when AUTH_SECRET is empty")
		}
	}()
	_ = IdentityFromCookie(IdentityMiddlewareConfig{
		AuthSecret:   "",
		CookieName:   fixtureCookieName,
		IdentityRepo: newFakeIdentityRepo(),
		Logger:       slog.New(slog.NewTextHandler(io.Discard, nil)),
	})
}

func TestIdentityFromCookie_Requires32ByteAuthSecret(t *testing.T) {
	// S-BAM-081: AUTH_SECRET shorter than 32 raw bytes is rejected.
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic when AUTH_SECRET is too short")
		}
	}()
	_ = IdentityFromCookie(IdentityMiddlewareConfig{
		AuthSecret:   "short",
		CookieName:   fixtureCookieName,
		IdentityRepo: newFakeIdentityRepo(),
		Logger:       slog.New(slog.NewTextHandler(io.Discard, nil)),
	})
}

// ---------------------------------------------------------------------------
// Sanity anchors
// ---------------------------------------------------------------------------

var _ = time.Second

// ---------------------------------------------------------------------------
// Lookup preference (R-BAM-010 + design §2.1):
// the middleware prefers LookupByProviderAccountID when the JWE carries
// `sub`; falls back to LookupByEmail when the canonical lookup misses.
// ---------------------------------------------------------------------------

func TestIdentityFromCookie_PrefersProviderAccountIDLookup(t *testing.T) {
	// R-BAM-010 + S-BAM-010 / S-BAM-041: when the JWE carries sub, the
	// middleware calls LookupByProviderAccountID first, NOT
	// LookupByEmail. The fake repo records both call counts so the
	// test asserts the ordering.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	logger, _ := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})
	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	if rec2.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d body=%q", rec2.Code, rec2.Body.String())
	}
	if repo.byProviderCalls != 1 {
		t.Errorf("expected LookupByProviderAccountID called once; got %d", repo.byProviderCalls)
	}
	if repo.byEmailCalls != 0 {
		t.Errorf("expected LookupByEmail NOT called (canonical lookup hit); got %d", repo.byEmailCalls)
	}
	if repo.lastProviderCall != "github" {
		t.Errorf("expected provider=github; got %q", repo.lastProviderCall)
	}
	if repo.lastProviderIDCall != "12345" {
		t.Errorf("expected accountID=12345; got %q", repo.lastProviderIDCall)
	}
}

func TestIdentityFromCookie_FallsBackToEmailOnProviderMiss(t *testing.T) {
	// When LookupByProviderAccountID misses (e.g., a stale cookie
	// minted before identity.account was populated), the middleware
	// falls back to LookupByEmail. This protects users during the
	// rollout window when PR-3 ships before all sessions refresh.
	jweValue := loadFixtureJWE(t)
	repo := newFakeIdentityRepo()
	// Force LookupByProviderAccountID to miss by emptying the fake's
	// map. LookupByEmail still has the fixture email.
	repo.byEmail = map[string]*domain.Identity{
		fixtureExpectedEmail: {
			ID:                42,
			Email:             fixtureExpectedEmail,
			Name:              "Octocat",
			ImageURL:          "https://github.com/avatars/octo.png",
			Provider:          "github",
			ProviderAccountID: "DIFFERENT_FROM_FIXTURE", // ensures provider lookup misses
		},
	}
	logger, _ := newCapturingLogger()
	_, tp := newSpanRecorder()
	t.Cleanup(func() { _ = tp.Shutdown(context.Background()) })

	e := newRouterWithAuth(IdentityMiddlewareConfig{
		AuthSecret:     fixtureAuthSecret,
		CookieName:     fixtureCookieName,
		IdentityRepo:   repo,
		Logger:         logger,
		TracerProvider: tp,
	})
	req := newRequestWithCookie(t, jweValue)
	rec2 := httptest.NewRecorder()
	e.ServeHTTP(rec2, req)

	if rec2.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d body=%q", rec2.Code, rec2.Body.String())
	}
	if repo.byProviderCalls != 1 {
		t.Errorf("expected LookupByProviderAccountID tried once; got %d", repo.byProviderCalls)
	}
	if repo.byEmailCalls != 1 {
		t.Errorf("expected LookupByEmail tried once as fallback; got %d", repo.byEmailCalls)
	}
	if repo.lastEmailCall != fixtureExpectedEmail {
		t.Errorf("expected email=%q; got %q", fixtureExpectedEmail, repo.lastEmailCall)
	}
}