/**
 * Security response headers.
 *
 * Reference: `sdd/security-vulnerability-remediation/spec/security-response-headers`.
 *   REQ-01 — emit CSP, X-Content-Type-Options, Referrer-Policy, X-Frame-Options
 *            on every response, and HSTS only when the request is forwarded
 *            over HTTPS.
 *   REQ-02 — validate the CSP against actual Qwik and Tailwind v4 output.
 *   REQ-03 — gate the internal API target log behind DEBUG=1.
 *
 * This module is a pure leaf (no external deps) so it can be unit-tested
 * without booting the Qwik server runtime. The Node server entry
 * (`src/entry.express.tsx`) imports `setSecurityHeaders` and wires it
 * as the first middleware in the request pipeline.
 *
 * CSP `'unsafe-inline'` rationale (REQ-02):
 *   - The Qwik SSR emits an inline `<script type="qwik/json">` payload
 *     per request that delivers the resumability state. Without
 *     `script-src 'unsafe-inline'` the browser refuses to evaluate
 *     it and hydration fails silently.
 *   - Qwik's optimizer does NOT yet emit nonce-based hashed scripts
 *     for the resumability payload, so a nonce CSP is not available
 *     without forking the build pipeline.
 *   - The risk is bounded: the inline script content is generated by
 *     the Qwik framework from the rendered HTML and is not user-
 *     controlled. Cross-site scripting through the inline payload
 *     requires first breaking the SSR pipeline, which is a separate
 *     threat class.
 *   - `style-src 'self' 'unsafe-inline'` mirrors the same reasoning
 *     for Tailwind v4 utility classes injected at runtime by the
 *     Tailwind CSS engine.
 *
 * If future work adds a nonce-based CSP, replace `'unsafe-inline'`
 * here and update the threat-model doc.
 */
import type { IncomingMessage, ServerResponse } from "node:http";

/**
 * The Content-Security-Policy directive string. Exported separately so
 * tests can pin the exact policy and reviewers can audit changes in
 * a single diff.
 */
export const CSP_DIRECTIVES =
  "default-src 'self'; " +
  "script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; " +
  "style-src 'self' 'unsafe-inline'; " +
  "img-src 'self' https: data:; " +
  "connect-src 'self' https: wss:; " +
  "frame-ancestors 'none'; " +
  "form-action 'self'";

/**
 * HSTS value applied when the request is forwarded over HTTPS.
 *   - max-age=63072000 = 2 years (Chrome's recommended minimum).
 *   - includeSubDomains = apply to every subdomain.
 */
const HSTS_VALUE = "max-age=63072000; includeSubDomains";

/**
 * Returns the security headers to apply for a given request, as a
 * plain `{ name: value }` map. Exposed so the proxy layer can
 * merge the headers into the upstream response (the `writeHead`
 * call on the proxy merges with previously set headers, but a
 * hostile upstream could otherwise re-introduce a permissive
 * `X-Frame-Options`; merging the security headers after the fact
 * keeps the contract authoritative).
 */
export function getSecurityHeaders(
  req: IncomingMessage,
): Record<string, string> {
  const headers: Record<string, string> = {
    "Content-Security-Policy": CSP_DIRECTIVES,
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "X-Frame-Options": "DENY",
  };
  if (req.headers["x-forwarded-proto"] === "https") {
    headers["Strict-Transport-Security"] = HSTS_VALUE;
  }
  return headers;
}

/**
 * Security-headers middleware. Sets the headers required by
 * `security-response-headers` REQ-01 on every outgoing response.
 *
 * HSTS is gated on `x-forwarded-proto: https` so HTTP dev / local
 * environments do not pin the browser to a fake HTTPS origin
 * (the spec protects against this by reading the header set by
 * the reverse proxy / load balancer; if absent, HSTS is omitted).
 */
export function setSecurityHeaders(
  req: IncomingMessage,
  res: ServerResponse,
  next: (err?: unknown) => void,
): void {
  const headers = getSecurityHeaders(req);
  for (const [name, value] of Object.entries(headers)) {
    res.setHeader(name, value);
  }
  next();
}
